homepy/urls.py
from django.urls import path
from . import views

app_name = "homepy"

urlpatterns = [
    path("", views.home, name="home"),
    path("edit", views.edit, name="edit"),
]

homepy/models.py
from django.db import models
from django.conf import settings


class HomeSettings(models.Model):

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    json = models.TextField(default="[]")

    def __str__(self):
        return "HomeSettings<%s>" % self.user
    

homepy/views.py
import datetime
import json
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import psutil
from piweb.decorators import require_app_access
from . import models


def uptime_to_str(td_):
    hours = td_.seconds // 3600
    minutes = (td_.seconds % 3600) // 60
    seconds = td_.seconds % 60
    return "%dd, %dh %dmin %ds" % (td_.days, hours, minutes, seconds)


def get_home_settings(request):
    if hasattr(request.user, "homesettings"):
        return request.user.homesettings
    return models.HomeSettings.objects.create(user=request.user)

def get_server_stats():
    boot_time = datetime.datetime.fromtimestamp(psutil.boot_time())
    return {
        "cpu": psutil.cpu_percent(),
        "ram": psutil.virtual_memory()._asdict()["percent"],
        "swap": psutil.swap_memory()._asdict()["percent"],
        "disk": psutil.disk_usage("/")._asdict()["percent"],
        "uptime": uptime_to_str(datetime.datetime.now() - boot_time),
    }

@require_app_access("homepy")
def home(request):
    home_settings = get_home_settings(request)
    links = json.loads(home_settings.json)
    return render(request, "homepy/home.html", {
        "links": links,
        "stats": get_server_stats()
    })


@require_app_access("homepy")
def edit(request):
    home_settings = get_home_settings(request)
    if request.method == "POST":
        home_settings.json = request.POST.get("json", [])
        home_settings.save()
    links = json.loads(home_settings.json)
    return render(request, "homepy/edit.html", {
        "links": links
    })

homepy/templates/homepy/edit.html
{% load static %}

<!DOCTYPE html>

<html>

<head>
    <title>Edit &mid; Homepy</title>
    <link rel="stylesheet" href="{% static 'piweb/css/master.css' %}" />
    <script type="text/javascript" src="{% static 'piweb/js/master.js' %}"></script>
</head>

<body class="bg-dark">

    <div>
        
        <div class="columns">

        <div class="column col-3 col-xs-12"></div>

        <div class="column col-6 col-xs-12">

        <p class="my-2">
            <a href="{% url 'homepy:home' %}" class="btn btn-primary">Home</a>
            <button class="btn btn-primary" onclick="addGroup()">Add Group</button>
            <button class="btn btn-primary" onclick="saveForm()">Save</button>
        </p>

        <div class="groups">
        
        {% for group in links %}
        
        <div class="container card my-2 p-2 group bg-secondary text-dark">

        <div class="group-header">
            <button class="btn btn-secondary" onclick="moveGroup(-1, this)">Move Up</button>
            <button class="btn btn-secondary" onclick="moveGroup(1, this)">Move Down</button>
            <button class="btn btn-secondary" onclick="addLink(this)">Add Link</button>
            <button class="btn btn-secondary" onclick="deleteGroup(this)">Delete Group</button>
        </div>

        <div class="group__links">

            {% for link in group.links %}
            
                <div class="input-group my-1 group__link">

                    <input class="form-input group__link__name" type="text" name="name" placeholder="Name" value="{{ link.name }}" />
        
                    <input class="form-input group__link__url" type="text" name="name" placeholder="URL" value="{{ link.url }}" />

                    <div class="px-2 group__link__type">
                        <label class="form-radio form-inline">
                            <input type="radio" value="static" name="type-{{ forloop.parentloop.counter }}-{{ forloop.counter }}" {% if link.type == 'static' %}checked{% endif %}><i class="form-icon"></i> Static
                        </label>
                        <label class="form-radio form-inline">
                            <input type="radio" value="dynamic" name="type-{{ forloop.parentloop.counter }}-{{ forloop.counter }}" {% if link.type == 'dynamic' %}checked{% endif %}><i class="form-icon"></i> Dynamic
                        </label>
                    </div>

                    <button onclick="deleteLink(this)" class="btn btn-clear" aria-label="Close"></button>
                
                </div>

            {% endfor %}
            </div>
            <div class="form-group">
            <label class="form-switch">
                <input type="checkbox" class="group__separator" {% if group.separator %}checked{% endif %}>
                <i class="form-icon"></i> Separator
            </label>
            </div>

        </div>
        
        {% endfor %}

        </div>

        <form action="" method="POST">
            {% csrf_token %}
            <input type="text" hidden name="json" value="" />
        </form>

        </div>
        <div class="column col-3 col-xs-12"></div>
        </div>


        <template id="link_template">
            <div class="input-group my-1 group__link">
                <input class="form-input group__link__name" type="text" name="name" placeholder="Name" value="" />
                <input class="form-input group__link__url" type="text" name="name" placeholder="URL" value="" />
                <div class="form-group px-2 group__link__type">
                    <label class="form-radio form-inline">
                        <input type="radio" value="static" name="type" checked><i class="form-icon"></i> Static
                    </label>
                    <label class="form-radio form-inline">
                        <input type="radio" value="dynamic" name="type"><i class="form-icon"></i> Dynamic
                    </label>
                </div>
                <button onclick="deleteLink(this)" class="btn btn-clear" aria-label="Close"></button>
            </div>
        </template>

        <template id="group_template">
            <div class="container card my-2 p-2 group bg-secondary text-dark">
                <div class="group-header">
                    <button class="btn btn-secondary" onclick="moveGroup(-1, this)">Move Up</button>
                    <button class="btn btn-secondary" onclick="moveGroup(1, this)">Move Down</button>
                    <button class="btn btn-secondary" onclick="addLink(this)">Add Link</button>
                    <button class="btn btn-secondary" onclick="deleteGroup(this)">Delete Group</button>
                </div>
                <div class="group__links"></div>
                    <div class="form-group">
                        <label class="form-switch">
                            <input type="checkbox" class="group__separator" {% if group.separator %}checked{% endif %}>
                            <i class="form-icon"></i> Separator
                        </label>
                </div>
            </div>
        </template>
    </div>

    <script type="text/javascript" src="{% static 'homepy/edit.js' %}"></script>
    <script type="text/javascript">
        bindDraggableOrdering(document.querySelector(".groups"), ".group");
    </script>

</body>

</html>

homepy/templates/homepy/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Home</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="{% static 'piweb/css/master.css' %}" />
    <style>
        canvas {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            right: 0;
            left: 0;
            bottom: 0;
            z-index: -1;
        }
    </style>
</head>

<body class="dark">
    <canvas class="connecting-dots"></canvas>
    <header class="container">
        <p class="text-right"><a href="{% url 'piweb:user' %}">@{{ request.user.username }}</a> &ndash; {% now "l, F jS" %} &ndash; {% now "H:i:s" %}</p>
    </header>
    <section class="container">
        {% if links %}
        {% for group in links %}
        <div>
            {% for link in group.links %}
            <a class="link-hidden" href="{% if link.type == 'static' %}{{link.url}}{% else %}{% url link.url %}{% endif %}"><span class="chip">{{link.name}}</span></a>
            {% endfor %}
        </div>
        {% if group.separator %}<br>{% endif %}
        {% endfor %} 
        {% else %}
        <p>
            You currently have no bookmark registered. <a href="{% url 'homepy:edit' %}">Add some over here.</a>
        </p>
        {% endif %}
    </section>
    {% if request.user.is_superuser %}
    <footer class="container p-fixed" style="right: 0; bottom: 0;">
        <p class="text-right">
            <code>UP {{stats.uptime}}</code>
            <br>
            <code>CPU {{stats.cpu|floatformat:0}}%</code> <code>RAM {{stats.ram|floatformat:0}}%</code> <code>SWAP {{stats.swap|floatformat:0}}%</code> <code>HDD {{stats.disk|floatformat:0}}%</code>
        </p>
    </footer>
    {% endif %}
    <script type="text/javascript" src="{% static 'homepy/dots.js' %}"></script>
</body>

</html>